version: '2'

services:

  postgres:
    image: postgres:9-alpine
    volumes:
       - relation_analyzer_db:/var/lib/mysql
    restart: always
    environment:
      POSTGRES_USER: ra
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata


  relation-analyzer:
    depends_on: 
        - postgres
    restart: always
    image: relation-analyzer
    ports:
      - 80:8080
    environment:
      DB_USER: ra
      DB_PASSWORD: example
      DB_NAME: postgres

volumes:
  relation_analyzer_db:
